jobs:
  run_sum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Installs required dependencies like @actions/core
        working-directory: ./  # Root directory (already correct)

      - name: Run Sum Action
        id: sum_step
        uses: sudarshan1212/sum-action@v1.0.0
        with:
          num1: 5
          num2: 5

      - name: Output Sum
        run: echo "The sum is ${{ steps.sum_step.outputs.sum }}"
