name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  synthetic_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Sum Action
        id: sum_step  # Added ID to reference outputs
        uses: sudarshan/sum-action@v1.0.0  # Make sure this repo exists and has a tag v1.0.0
        with:
          num1: 5
          num2: 3

      - name: Output Sum
        run: echo "The sum is ${{ steps.sum_step.outputs.sum }}"
