name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  run_sum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Sum Action
        id: sum_step  # ID to reference outputs
        uses: sudarshan1212/sum-action@v1.0.0  # Make sure this repo exists and has a v1.0.0 tag
        with:
          num1: 5
          num2: 10

      - name: Output Sum
        run: echo "The sum is ${{ steps.sum_step.outputs.sum }}"
